### ISSUE TITLE
Servo doesn't adjust speeds correctly on continuous rotation servos

### ISSUE THREAD

**Issue by zsup** [spark/firmware#120]
At RobotsConf, many people were working with the Servo library using robots driven by continuous rotation servos. Theoretically the way they should work is that servo.write(0) should turn one direction, servo.write(90) should stop the servo, and servo.write(180) should turn the other direction. This worked correctly if the servo was calibrated appropriately.

However, in the case above, servo.write(91) should move very slowly in one direction, and servo.write(89) should move very slowly in the other direction. This behavior was not observed; instead, it seemed like servo.write functions always moved the continuous rotation servo at full speed, but just in different directions.

**Comment by m-mcgowan** [comment]
Anyone know if this has been resolved? cc: @satishgn, @technobly

**Comment by technobly** [comment]
@m-mcgowan I don't have any continuous rotation servos on hand to test this on, but I'm guessing this is most likely an issue with the servo if it doesn't move slowly at pulse widths near "center".  Also, for that to properly work, the servo would need to be precisely calibrated to the pulse width that servo.write(90) outputs as "center".  Based on the tolerance of the servo PWM output, this may not be completely in line with what the servo expects.

It would be best to analyze this problem by sending me a few of the servos that were used at RobotsConf that had issues... hopefully they are servos with a decent datasheet.  I'll use a scope and figure it out :)

**Comment by technobly** [comment]
Ok so I nabbed up the two servos continuous rotation that Adafruit sells and tested them.  They work fine!  The issue is well stated as @zsup said where `servo.write(90);` does not make the servo stop.  However, I was able to make these servos stop, creep in either direction and go all of the way to full speed; but the center position value varied between them.  The large standard size servo needed to be set to exactly 95 to be stopped, where 94 and 96 would creep in either direction.  The micro servo was stopped between 90 and 98, and would creep in either direction at 89 and 99.

Each servo responds a little differently, and I think this could just be a tolerance issue.  Every RC Transmitter I've ever known has analog or digital trimmers on the different output channels, which essentially sets the neutral output pulse value.  Similar concepts could be implemented in the software to make something like `servo.write(90+trim);` actually stop servo.

What the user needs is a straight forward way to control a servo and determine what values stop the servo, and make it creep in either direction or move and full speed in either direction.  What to do with the range of values in between is really up to the user to implement, eg., proportional control or a low - med - high setting... etc..

What follows is a modified version of Tinker that allows you to control a servo using the Particle iOS or Android app.  

### 1. Program the Tinker Servo app to your Photon or Core

### 2. Hook up the servo
* CONTROL to D0 pin
* VCC to VIN pin
* GND to GND pin

### 3. Open the Particle or Spark Core app and set up the pins
* D0 = analogWrite (a 0 - 180 control slider for corse servo position adjustment)
* A2 = analogRead (tap to increment and return the current servo position by 1)
* A1 = analogRead (tap to only return the current servo position)
* A0 = analogRead (tap to decrement and return the current servo position by 1)

### 4. Use it!
Using the above controls, you can very easily play with your servo and characterize its output, based on input `servo.write(pos)` values (0 - 180).  You can find the center `off` value, creep and full speed values.  Values greater than 180 on the D0 slider will be bound to 180, but still display in the iOS or Android app as the higher value.  Tap A1 to confirm the servo is set to 180. Tap A2 to increment the value by 1, or tap A0 to decrement it by 1.

--- 

## Tinker Servo app
```c++
/**
 ******************************************************************************
 * @file    application.cpp
 * @authors Satish Nair, Zachary Crockett, Mohit Bhoite and Brett Walach
 * @version V1.0.0
 * @date    16-June-2015
 * @brief   Tinker Servo application
 ******************************************************************************
  Copyright (c) 2013-2015 Particle Industries, Inc.  All rights reserved.

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation, either
  version 3 of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this program; if not, see <http://www.gnu.org/licenses/>.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/  
#include "application.h"

/* ========================
 * SPECIAL SERVO CODE ON D0
 * ======================== 
 */
Servo myservo;  // create servo object to control a servo
                // a maximum of eight servo objects can be created
int pos = 0;    // variable to store the servo position

/* Function prototypes -------------------------------------------------------*/
int tinkerDigitalRead(String pin);
int tinkerDigitalWrite(String command);
int tinkerAnalogRead(String pin);
int tinkerAnalogWrite(String command);

/* This function is called once at start up ----------------------------------*/
void setup()
{
    setADCSampleTime(ADC_SampleTime_480Cycles);
	//Setup the Tinker application here

	//Register all the Tinker functions
	Spark.function("digitalread", tinkerDigitalRead);
	Spark.function("digitalwrite", tinkerDigitalWrite);

	Spark.function("analogread", tinkerAnalogRead);
	Spark.function("analogwrite", tinkerAnalogWrite);

    /* ========================
     * SPECIAL SERVO CODE ON D0
     * ======================== 
     */
    myservo.attach(D0);  // attaches the servo on the D0 pin to the servo object
}

/* This function loops forever --------------------------------------------*/
void loop()
{
	//This will run in a loop
}

/*******************************************************************************
 * Function Name  : tinkerDigitalRead
 * Description    : Reads the digital value of a given pin
 * Input          : Pin 
 * Output         : None.
 * Return         : Value of the pin (0 or 1) in INT type
                    Returns a negative number on failure
 *******************************************************************************/
int tinkerDigitalRead(String pin)
{
	//convert ascii to integer
	int pinNumber = pin.charAt(1) - '0';
	//Sanity check to see if the pin numbers are within limits
	if (pinNumber< 0 || pinNumber >7) return -1;

	if(pin.startsWith("D"))
	{
		pinMode(pinNumber, INPUT_PULLDOWN);
		return digitalRead(pinNumber);
	}
	else if (pin.startsWith("A"))
	{
		pinMode(pinNumber+10, INPUT_PULLDOWN);
		return digitalRead(pinNumber+10);
	}
	return -2;
}

/*******************************************************************************
 * Function Name  : tinkerDigitalWrite
 * Description    : Sets the specified pin HIGH or LOW
 * Input          : Pin and value
 * Output         : None.
 * Return         : 1 on success and a negative number on failure
 *******************************************************************************/
int tinkerDigitalWrite(String command)
{
	bool value = 0;
	//convert ascii to integer
	int pinNumber = command.charAt(1) - '0';
	//Sanity check to see if the pin numbers are within limits
	if (pinNumber< 0 || pinNumber >7) return -1;

	if(command.substring(3,7) == "HIGH") value = 1;
	else if(command.substring(3,6) == "LOW") value = 0;
	else return -2;

	if(command.startsWith("D"))
	{
		pinMode(pinNumber, OUTPUT);
		digitalWrite(pinNumber, value);
		return 1;
	}
	else if(command.startsWith("A"))
	{
		pinMode(pinNumber+10, OUTPUT);
		digitalWrite(pinNumber+10, value);
		return 1;
	}
	else return -3;
}

/*******************************************************************************
 * Function Name  : tinkerAnalogRead
 * Description    : Reads the analog value of a pin
 * Input          : Pin 
 * Output         : None.
 * Return         : Returns the analog value in INT type (0 to 4095)
                    Returns a negative number on failure
 *******************************************************************************/
int tinkerAnalogRead(String pin)
{
	//convert ascii to integer
	int pinNumber = pin.charAt(1) - '0';
	//Sanity check to see if the pin numbers are within limits
	if (pinNumber< 0 || pinNumber >7) return -1;

	if(pin.startsWith("D"))
	{
		return -3;
	}
	else if (pin.startsWith("A"))
	{
		/* ==================================
		 * SPECIAL SERVO FEEDBACK ON A0 ~ A2
		 * A2 Increments and returns position
		 * A1 only returns position
		 * A0 Decrements and returns position
		 * ================================== 
		 */
		if (pinNumber == 2) {
		    if (pos < 180) pos++;
		    myservo.write(pos); // tell servo to go to position in variable 'pos'
		    return pos; // Returns current servo D0 position
		}
		else if (pinNumber == 1) {
		    return pos; // Returns current servo D0 position
		}
		else if (pinNumber == 0) {
		    if (pos > 0) pos--;
		    myservo.write(pos); // tell servo to go to position in variable 'pos'
		    return pos; // Returns current servo D0 position
		}
		return analogRead(pinNumber+10);
	}
	return -2;
}

/*******************************************************************************
 * Function Name  : tinkerAnalogWrite
 * Description    : Writes an analog value (PWM) to the specified pin
 * Input          : Pin and Value (0 to 255)
 * Output         : None.
 * Return         : 1 on success and a negative number on failure
 *******************************************************************************/
int tinkerAnalogWrite(String command)
{
	//convert ascii to integer
	int pinNumber = command.charAt(1) - '0';
	//Sanity check to see if the pin numbers are within limits
	if (pinNumber< 0 || pinNumber >7) return -1;

	String value = command.substring(3);

	if(command.startsWith("D"))
	{
		/* ========================
		 * SPECIAL SERVO CODE ON D0
		 * ======================== 
		 */
		if (pinNumber == 0) {
		    pos = value.toInt();
		    if (pos > 180) pos = 180;
		    myservo.write(pos); // tell servo to go to position in variable 'pos'
		}
		else {
		    pinMode(pinNumber, OUTPUT);
		    analogWrite(pinNumber, value.toInt());
		}
		return 1;
	}
	else if(command.startsWith("A"))
	{
		
		pinMode(pinNumber+10, OUTPUT);
		analogWrite(pinNumber+10, value.toInt());
		return 1;
	}
	else return -2;
}
```

**Comment by m-mcgowan** [comment]
Implemented with Servo.trim(), which provides the finest control by allowing the length of the pulse to be adjusted.
