### ISSUE TITLE
SPISettings gone missing with 0.6.2-rc.1 (and all following)

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#1381]
I just tried to recompile an old sketch which was using `SPISettings()` and worked woth 0.6.1, but with 0.7.0-rc.3 I got 
```
'SPISettings' was not declared in this scope
```
And after backtracking I found that 0.6.1 (including RCs) was the first ***and*** last version that supported that.

However, when *also* adding
```
#include "Arduino.h"
```
we are back in the game, but that's still counterintuitive, isn't it?

**Comment by m-mcgowan** [comment]
This is by design. SPISettings were added late in the game, which broke some libraries and applications that were already defining them. 0.6.2-rc.1 introduced Arduino compatibility via the Arduino header, along with the `ARDUINO` version define that library authors use to determine which arduino features are available.

**Comment by ScruffR** [comment]
In that case the docs are omitting this crucial information tho'

**Comment by technobly** [comment]
@ScruffR how does this sound? https://github.com/spark/docs/issues/681

**Comment by ScruffR** [comment]
Yup, that may do (more see in spark/docs#681)

**Comment by m-mcgowan** [comment]
Can we close this one now?

**Comment by ScruffR** [comment]
I'm still not completely convinced, but will have to put up with it.
