### ISSUE TITLE
Persist cache of last successfully connected Cloud server IP

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#139]
As of 2 March 2014 with latest firmware, we can store Cloud server IP or domain name on external flash.  Fallbacks are hard coded, first to "device.spark.io" then to 54.208.229.4.

An additional layer of robustness suggested by @andyw-lala is a persistent cache of an IP to which the Core recently successfully connected.

This datum is probably a good candidate for the CC3000 EEPROM.

**Comment by m-mcgowan** [comment]
The present connection logic first determines which IP to connect to and then tries to connect to that. In pseudo code:

- is there server address info stored in flash?
 - if it's a domain name, resolve to an IP (which may fail)
 - else use the IP as is
- if no IP is set, use the default (54.208.229.4)

The biggest weakness here is if the DNS lookup fails, in which case I feel we should not fallback to the default IP, but rather fail the connection, or the device may unexpectedly switch servers due to errors in the external environment (DNS).

cc: @joegoggins

**Comment by joegoggins** [comment]
Thank you for clarifying this logic @m-mcgowan and proposing that we eliminate the default IP, I completely agree with you.  

In addition to the benefit this would have to the firmware and device behavior, this would also simplify cloud-side requirements and allow us to do better, more efficient balancing, server-localization, and failover of device connections via DNS. Whereas doing these same things with a static IP are much more difficult and less robust to failure.

Strong   :+1: :shipit: from me on this one.

**Comment by bkobkobko** [comment]
So my only concern is that DNS fails in a bad way on certain TI CC3000 chips with certain links.  And once it fails, it can only be recovered (as far as I can tell) by re-flashing the latest TI patch.

It is easy to tell when the TI part has failed since the IP address of the DNS host is always 76.83.0.0.

You guys should factor that into your thinking on this one since today a core with a bad DNS host can connect to the cloud and be reflashed but you will not be able to do that after a change like this.

**Comment by m-mcgowan** [comment]
Thanks @bkobkobko for articulating the worries that I had in the back of my mind! 

What we can do in this instance is in the `inet_gethostname()` function, check if the hostname matches our primary cloud hostname, and if the lookup fails, and the DNS host is 76.83.0.0 then fallback to the default IP.  This will keep open the cloud connection for devices with failed DNS resolution.

This is a lot nicer than the current default IP logic since it only comes into play during a known error condition with the cc3000.

**Comment by m-mcgowan** [comment]
I re-read @bkobkobko's comment now - I see that it's the DNS host and not the result from inet_gethostname() that has the bogus IP address. Not sure what we can do when establishing a cloud connection other than rely upon the hard-coded IP address that's used when DNS lookup fails.

**Comment by m-mcgowan** [comment]
Addressed in this commit https://github.com/spark/firmware/commit/2042446ef2db1afed13a37b6e61093e2dc545d2b.  I never had a Core with the DNS lookup problem - if anyone has, much obliged if you could test this commit and verify the Core still connects to the cloud.

**Comment by m-mcgowan** [comment]
We will remove the default fallback IP if DNS lookup fails and instead fail the connection.

**Comment by towynlin** [comment]
Big 👍 to this at this time. It's been long enough. We first need to get the fallback IP out of new firmware. Once the firmware version sans fallback IP is widely enough used by devices, we can evaluate how to continue to reduce usage of that IP in our cloud.

**Comment by joegoggins** [comment]
Thanks for re-opening this Mat, if there are any other uses or references to 54.208.229.4 (the fallback IP) in the code if you can remove while you are in there too that'd be sweet. 

For others following along, the reason for this change is because scaling an IP based setup is much harder than scaling something that uses DNS--if we can assume everything uses DNS for resolution, it allows us to make make stronger high-availability/connectivity guarantees.

**Comment by technobly** [comment]
Closing now that this is merged in v0.6.0-rc.2!
