### ISSUE TITLE
Compiler getting confused by a String

### ISSUE THREAD

**Issue by zsup** [spark/firmware#146]
See here: https://community.spark.io/t/having-trouble-compiling-code-on-spark-that-works-on-arduino/3328/3

**Comment by m-mcgowan** [comment]
The `operator=(String&& s)` method is a new C++11 method that takes an rvalue-reference. 
The compiler sees the method declaration, but not the implementation, which then causes the linker error that we see.

When compiling user code compiler sees the declaration of the String&& methods, because the makefile template for the compile server passes `-std=gnu++0x` to each cpp file built in the user project, meaning they see the rvalue-reference functions that were guarded with c++11 checks.  However, the make recipe for the firmware doesn't define `-std=gnu++0x`, so when `spark_wiring_string.cpp` is compiled, the c++11 support is disabled, meaning the String&& methods are not compiled into the object file, and thus not available to the linker.

The fix is to enable c++11 support for both the core firmware and user application code. This is done in the feature/hal branch and will be available next release.

**Comment by m-mcgowan** [comment]
Fixed in 0.4.0
