### ISSUE TITLE
Implement mode that connects to cloud but doesn't run user code

### ISSUE THREAD

**Issue by WillWill56** [spark/firmware#208]
Since it is possible to send a program to the Spark Core from spark.io/build that disrupts the Core's connection to the cloud, I think it would be useful to be able to boot the Core into a mode where it connects to the cloud but doesn't run setup() and loop(), so that new code can still be flashed OTA instead of resorting to DFU mode (or factory reset).

It could be as simple as holding MODE and RST down, releasing RST, then releasing MODE in less than 3 seconds (since after 3 seconds is DFU mode).

**Comment by m-mcgowan** [comment]
@jenesaisdiq  - any thoughts on this?

The issue proposes "safe mode" that the user activates by holding mode on startup for at least 1 second, but less than 3 (which takes the user into dfu mode/flashing yellow.) 

Brett proposed, flashing magenta LED - to me this is related to OTA update. I suggest flashing cyan, to indicate that on boot the device will connect to the cloud.

Some of the changes are in the bootloader, so need a response urgently if this is to make it for the upcoming photon release.

**Comment by m-mcgowan** [comment]
There's some misunderstanding here - I'll try to clarify 

- the flashing led is because the core hasn't booted yet - flashing is then consistent with the other startup modes that flash the led different colors depending upon how long mode has been held:

  - 1-3s : flashing ??? (cyan/magenta) - new proposed safe mode
  - 3s-6s : flashing yellow - DFU mode 
  - 6s-10s: flashing green - factory restore mode (restore the factory firmware, but don't erase WiFi creds.)
 - > 10s: flashing white - full factory reset (restore the factory firmware, and erase WiFi creds and all other data.)

These modes are only ever manually selected by the user by pressing and holding MODE during a reset.

(I have made it so that if the system does a factory restore due to bad user firmware, it doesn't erase WiFi settings.)

**Comment by jenesaisdiq** [comment]
Ok, so in this mode neither Spark loop nor user loop is running? Or is the Spark loop running with WiFi active so that OTA is possible?

**Comment by m-mcgowan** [comment]
It's the latter - the system loop runs, but not the user setup() or loop() function so that the core isn't interrupted by possibly broken user code. The core can then connect to the cloud and perform an OTA.

**Comment by m-mcgowan** [comment]
I'm wondering if this need isn't already met by the factory restore mode? 

The use case for maintaining a separate safe mode is that the user is able to flash their own firmware as factory backup, which may also inadvertently be bad, preventing connection to the cloud. Safe mode won't run user portion of the firmware and will default to Automatic mode, pretty much guaranteeing connection to the cloud regardless of the state of the user firmwares on the device.

**Comment by jenesaisdiq** [comment]
Right, and I've seen this many, many times. I like the idea of having it, saves me the annoyance of a factory reset procedure. Breathing magenta makes sense for this; it's related flashing code (from the user's perspective) and it's in an expected, desired stable state.

**Comment by m-mcgowan** [comment]
The factory restore is more convenient than a factory reset since you don't have to enter Wifi credentials again. Can you confirm that's not enough?

If we go for breathing magenta, it will only last for the 2 seconds that the user has to release the mode button to leave the bootloader and start booting firmware in safe mode. When the mode button is released the core will then go through the usual led colors and patterns as it connects to the cloud - white, green, cyan etc. If the mod button isn't released then the next step is flashing yellow (DFU mode.)

I wonder if breathing the LED for 2 seconds might appear odd compared to simply flashing - flashing gives immediate feedback, so the user can see clearly they will select safe mode when releasing the mode button at that time. Breathing is much softer so it might not be obvious that the user has to react now and release the mode button to select that mode.

**Comment by jenesaisdiq** [comment]
How's a factory restore triggered?

And I see, you can't have it breathe magenta _after_ it's gone through the safe boot process to indicate, it's just as you pass through to indicate what mode it will be in if you release the setup button at that point.  Solid magenta, then? Would like to use a pattern that doesn't currently have a mapping.

**Comment by m-mcgowan** [comment]
Factory restore is triggered by holding setup for 6s - the led flashes green. There's a list of startup modes above (https://github.com/spark/firmware/issues/208#issuecomment-89843804). Factory restore is a relatively new addition - the color can be changed if desired. I chose green to associate with wifi credentials/connectivity still working after the reset.

Solid magenta might work for safe mode, although solid LEDs do look like the device has crashed and is unresponsive. Can I try to persuade you towards flashing either cyan or magenta? :-)

Pros for flashing cyan:

- currently, flashing cyan means connecting to the cloud - which is what the device will do once you let go of the setup button
- the color at the start is cyan and so the color at the end of the process, providing cohesion and a strong association between the startup mode and the final state of the device.

If we view the process as including the OTA update, then flashing magenta could work for similar reasons:

- flashing magenta is associated with OTA updates, which is our main envisaged use case for safe mode (although possibly not the only use case - the user might want to also enter listening mode that is prevented by their crashy firmware.)
- flashing magenta at the start, and at the end of the process (once the user has initiated an OTA update.)

Imho, magenta is less appealing since the rest state of the device is cyan until the user starts an OTA update.

With the user manually choosing a startup mode, reusing existing LED patterns reinforces the the already understood meaning and builds a strong connection with the target device state. I feel this is easier and more meaningful for the user compared to finding a new pattern the user has to remember.

**Comment by jenesaisdiq** [comment]
Cool, convinced enough. I think the magenta will be more distinctive, but the flashing cyan also makes sense to me. Do the cyan.

**Comment by m-mcgowan** [comment]
Satish and I will code it up tomorrow and we can see what it looks like in the flesh.

**Comment by m-mcgowan** [comment]
Implemented in manufacturing bootloader. The color ended up being flashing magenta, since it was a bigger contrast to yellow compared with cyan -> yellow ! :-)
