### ISSUE TITLE
Default Initializer Coding Style

### ISSUE THREAD

**Issue by technobly** [spark/firmware#218]
There are two different ways to create a default argument.  One way is to create a separate overloaded method that calls calls the other method with the default value such as how it's done a lot in the spark_wiring_time.cpp TimeClass.

```cpp
/* current hour */
int TimeClass::hour()
{
	return hour(now());
}

/* the hour for the given time */
int TimeClass::hour(time_t t)
{
	Refresh_UnixTime_Cache(t);
	return calendar_time_cache.tm_hour;
}
```

Another way which works as well is just setting the default value of the argument in the method prototype.  If the argument is not specified, the default is used.

```cpp
static int     hour(time_t t = now());				// the hour for the given time
```

I realize the second method is not CLS-compliant from Microsoft's point of view, but is there a specific reason Spark doesn't use this second method for core-firmware?  In my limited testing, the second method creates a slightly smaller compiled binary.

**Comment by m-mcgowan** [comment]
My vote is for default arguments - it reduces the amount of code and encapsulates the semantics better - we can clearly see it's a default value.

Although specifically for this class, I'd say it's a poor choice since the time is going to change for every single invocation, so calling month(), day(), hour(), minute(), second() may return bogus data if the time happens to change between each method call. So I would prefer not to have no-arg versions of these, and instead always require the user to pass in a time, so we can be certain of consistency.

**Comment by m-mcgowan** [comment]
@technobly and I talked more on this today and concluded that our default style should be to use default parameters, rather than method overloading.

The only reason we could think of why method overloading would be preferred is if we eventually want to target the CLR that requires CLS-compliant code. If that transpires, we can simply rework the default arguments to method overloads.

**Comment by technobly** [comment]
:+1:

**Comment by andyw-lala** [comment]
Sheesh - loading firmware down with requirements from .NET and M$oft ?
That's crazy talk.

On Thu, Apr 30, 2015 at 1:54 PM, Matthew McGowan <notifications@github.com>
wrote:

> @technobly <https://github.com/technobly> and I talked more on this today
> and concluded that our default style should be to use default parameters,
> rather than method overloading.
>
> The only reason we could think of why method overloading would be
> preferred is if we eventually want to target the CLR that requires
> CLS-compliant code. If that transpires, we can simply rework the default
> arguments to method overloads.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/218#issuecomment-97925668>.
>



-- 
Andy

**Comment by technobly** [comment]
It's the only default parameter / method overloading "standard" I found.  If you know of others please tack them on below.  Or if you have opinions of one vs. the other, please chime in!

**Comment by andyw-lala** [comment]
Whatever results in the cleanest, smallest, fastest code should be the
primary/only criteria.

How does gcc do default parameters these days ? Different entry points
still ? If so, I see it as being able to be marginally more efficient than
method overlapping in terms of footprint when multiple entry points are
used concurrently. The compiler knows to only duplicate the preamble, not
the whole function, whereas the method overloading relies on the programmer
to do so, and lazy cut/paste will likely lead to bloat and stupid errors.

Of course, this may all be moot because of some funky new fangled gcc
technique.

On Thu, Apr 30, 2015 at 2:19 PM, Technobly <notifications@github.com> wrote:

> It's the only default parameter / method overloading "standard" I found.
> If you know of others please tack them on below. Or if you have opinions of
> one vs. the other, please chime in!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/218#issuecomment-97934548>.
>



-- 
Andy
