### ISSUE TITLE
simple UDP broadcasting program dies, probably shouldn't 

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#240]
UDP Udp;

unsigned char TxMsg[12] = { 1, 254, 1, 254, 1, 254, 43, 212, 71, 184, 3, 252 };
unsigned char recbuf[12];

void setup() {
    Udp.begin(9000);
    pinMode(D7, OUTPUT);
    digitalWrite(D7, LOW);
}

void loop() {
    int32_t packetLen = Udp.parsePacket();

    //Dump any packets RX
    while (packetLen > 0) {
        Udp.read(recbuf, packetLen >= 12 ? 12 : packetLen);
        packetLen = Udp.parsePacket();
    }

    Udp.beginPacket(IPAddress(10,0,0,2), 9000);
    Udp.write(TxMsg, 12);
    Udp.endPacket();

    digitalWrite(D7, HIGH);
    delay(200);
    digitalWrite(D7, LOW);
    delay(200);
}

**Comment by m-mcgowan** [comment]
Has anyone tried with the latest service pack 1.14?

**Comment by SomeFixItDude** [comment]
Are we getting another deep update for the spark core cc33k?  I just checked on the the web ide and didn't see one yet.  I don't know how long that patch has been out either.

**Comment by m-mcgowan** [comment]
We'll be making a new deep update available after it's had some testing. Before then, the 1.14 patch can be downloaded from https://github.com/spark/cc3000-patch-programmer/blob/ti-patch-1.14/build/cc3000-patch-programmer.bin?raw=true   (That's a direct download link.)

[Deploy instructions](https://github.com/spark/cc3000-patch-programmer/tree/ti-patch-1.14)

**Comment by SomeFixItDude** [comment]
@m-mcgowan, has there been a successful test with the program provided?  I have not but I am waiting for the official deep update to come out.  Unless you have tested?  Otherwise can you keep this issue open please?

**Comment by m-mcgowan** [comment]
the 1.14 update is available in the CLI - `particle flash --usb cc3000_1_14`. Much appreciated if you're able to verify this with the code.  bko mentioned that the code works if you also read the data, so figured that was a sufficient workaround.

**Comment by SomeFixItDude** [comment]
Thanks @m-mcgowan - I'll try to get some time this week.  The code "works" when you read the data is if you use the broadcast address and is not how the orig program operates. 

Orig:
Udp.beginPacket(IPAddress(10,0,0,2), 9000);

bko changed it
bko's:
int beginReady = Udp.beginPacket(IPAddress(10,0,0,255), 9000);  //works-change 255 to 10 to fail

The orig program was meant to send a udp packet to another host (not itself) and not broadcast / multicast.  This part: 

//Dump any packets RX
while (packetLen > 0) {
    Udp.read(recbuf, packetLen >= 12 ? 12 : packetLen);
    packetLen = Udp.parsePacket();
}

shouldn't even need to exist and was put in place as voodoo.  We should be able to craft a udp packet up and send it rapidly.  The orig code has it all slowed down and was/is still failing.  Any modifications really shouldn't be necessary involving stopping, flushing, and or tearing down the udp object and re-establishing...  All that overhead kills the speed benefit of udp.

Anyway if we go workaround route, I still don't want to broadcast but unicast.  The "working" version does the broadcast.  I'll try to give it a go this week, crossing fingers that it works.

Thanks!

**Comment by andyw-lala** [comment]
You can try listening to a different port, that way the stack should just
throw it away because there is no listener.

At this point you've explicitly told the Udp class to listen on port 9000,
and it's kinda doing what it was asked to.

However, it's still going to listen on _some_ port, so it's wise to throw
all the data away anyway (because it looks like the protocol stack in the
CC3000 will try and store the data, then gets into trouble because it runs
out of space...)

On Wed, Sep 30, 2015 at 12:49 PM, Brian Dilks <notifications@github.com>
wrote:

> Thanks @m-mcgowan <https://github.com/m-mcgowan> - I'll try to get some
> time this week. The code "works" when you read the data is if you use the
> broadcast address and is not how the orig program operates.
>
> Orig:
> Udp.beginPacket(IPAddress(10,0,0,2), 9000);
>
> bko changed it
> bko's:
> int beginReady = Udp.beginPacket(IPAddress(10,0,0,255), 9000);
> //works-change 255 to 10 to fail
>
> The orig program was meant to send a udp packet to another host (not
> itself) and not broadcast / multicast. This part:
>
> //Dump any packets RX
> while (packetLen > 0) {
> Udp.read(recbuf, packetLen >= 12 ? 12 : packetLen);
> packetLen = Udp.parsePacket();
> }
>
> shouldn't even need to exist and was put in place as voodoo. We should be
> able to craft a udp packet up and send it rapidly. The orig code has it all
> slowed down and was/is still failing. Any modifications really shouldn't be
> necessary involving stopping, flushing, and or tearing down the udp object
> and re-establishing... All that overhead kills the speed benefit of udp.
>
> Anyway if we go workaround route, I still don't want to broadcast but
> unicast. The "working" version does the broadcast. I'll try to give it a go
> this week, crossing fingers that it works.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/240#issuecomment-144489103>.
>



-- 
Andy

**Comment by SomeFixItDude** [comment]
@andyw-lala, but I am sending to another host ip address.  I should not be getting anything in my receive buffer at all.  Core is on 10.0.0.30 sending a udp packet to 10.0.0.2.

Anyway, I am keeping the read and dump of anything I pickup from udp.  In my controlled environment I know I am the only sender, but I don't know this in other environments.  So I have that reading and discarding code still in place for the sake of some other application happens to use the same port and is broadcasting, I don't want to crater.

I do plan on moving over to the photon so hopefully all the weird udp quirks won't be over there.

Again, Thanks all for your time.

**Comment by AlanGitMan** [comment]
I'm going to piggy back on this topic rather than creating a new one - cos all this kind of seems related....

I have global declarations like:

IPAddress remoteIP(192,168,1,255); // Events broadcast address;
int remotePort = 1900; 

Then, I have a function like this.

// Send a broadcast message on the WAN containing the supplied status string.
void mysendLog(char* theBuffer)
{
    UDP udp;
    udp.begin(5000);
    udp.flush();
	udp.beginPacket(192.168.1.255,remotePort);
	for (int x=0;x<=strlen(outBuff);x++)
	{
		udp.write(outBuff[x]);
	}    
	udp.endPacket();
	udp.flush();
	udp.stop();
}

which I use on a two SparkCores (not Particles).
This works fine for one or the other of the cores. i.e. if (On my ubuntu system) I use the command:

   nc -l -u 192.168.1.255 1900 

I see the status messages (70 characters or so, once per minute) coming through fine - but only for one or other of the cores - never both.  EITHER core can be the winner, seems to be whichever gets on the network first. Messages from the losing core never appear in the log stream. 

Now, perhaps I am misunderstanding something here - but surely a broadcast address is fully shareable? Either core (or any other device) should be able to push UDP messages over it? I'm assuming that udp.stop() closes the port since there is no udp.close()? But surely, in any case since the UDP connection is local to the function, that object and any connections are destroyed when the function ends? Clearly I am misunderstanding something here. Can anyone help lighten my darkness...?

Thanks in advance
Alan T
Cornwall UK.

**Comment by SomeFixItDude** [comment]
@AlanGitMan I have had success using this method for both broadcast and unicast.  Just change the ip in this example.  I think the flush after your endPacket might be a problem but I am not sure...

void sendTemp() {
    if (WiFi.ready()) {
        //012345678901
        //!^T^D^S^D^F^
        unsigned char TxMsg[12] = {33, 222, 84, 0, deviceId, 0, 0, 0, 0, 0, 0, 0 };

        TxMsg[6] = currentTemp < 0 ? 45 : 43;
        TxMsg[8] = (currentTemp / 10);
        TxMsg[10] = (currentTemp % 10);
        
        for (unsigned char i=2; i <= 10; i+=2)
            TxMsg[(i + 1)] = TxMsg[i] ^ 255;

        Udp.begin(9000);
        Udp.beginPacket(IPAddress(10,0,0,20), 9000);
        Udp.write(TxMsg, 12);
        Udp.endPacket();
        delay(10);
        Udp.stop();
        
        digitalWrite(D7, HIGH);
        delay(20);
        digitalWrite(D7, LOW);
    }
}

I particularly don't like the delay(10) I have in there (voodoo-ish) but the above seems to work.  Give that logic block but tweaked for your process a try.

Good Luck!
