### ISSUE TITLE
spark.process required in semi-automatic mode?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#306]
re this thread:
https://community.spark.io/t/tcpclient-panic-when-in-semi-automatic-wireless-mode/6893/3

**Comment by m-mcgowan** [comment]
Spark.process() definitely isn't required in semi automatic mode, but calling it does no harm, it simply runs the protocol event loop.

My best guess is that running the event loop early helps sidestep a timing issue with the cc3000. E.g. pulling cloud data/events before the TCPClient use so that the TCP buffers are free to service the TCPClient.

**Comment by m-mcgowan** [comment]
Not reproducable.
