### ISSUE TITLE
Spark Core can't send multicast UDP packets without connecting to the cloud first

### ISSUE THREAD

**Issue by benwis** [spark/firmware#348]
I've been trying to use the Spark Core to send SSDP(UPD broadcast) packets to 239.255.255.250 and discover the IP of a Sony camera. Trouble is, I can only send the packets in AUTOMATIC MODE. If I connect to the Wi-Fi using manual mode, the packet's just don't send unless I've connected or previously have connected to the Cloud. Regular UDP packets to a fixed IP work fine in manual mode.

Example code can be found here:
https://community.spark.io/t/spark-core-send-udp-ssdp-packet-correctly/8070/15
https://community.spark.io/t/udp-broadcasts-and-system-mode-manual/7712
https://community.spark.io/t/udp-broadcast-only-works-when-connected-to-the-cloud-why/7971/8

 I can't figure out why UDP broadcast would require a cloud connection at some point. I need to be able to do it without a WiFi connection. Can anyone offer a fix/reason?

EDIT: Updated terminology according to psb777

**Comment by m-mcgowan** [comment]
From knowing the code, there is nothing that we are doing that would prevent UDP multicast from working until the cloud is connected. 

If someone has time to test with the latest CC3000 driver 1.14 (1.32 host driver) which fixes many issues, that would be much appreciated. For now, I'm calling this closed since applying a service pack is our only resolution here.
