### ISSUE TITLE
Warning for exceeding defined limits

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#351]
Suggestion to have a warning by the compiler if the user exceeds the number of Spark.functions /limit on features they can use.

See community thread:

https://community.spark.io/t/spark-function-limits/952/14

**Comment by m-mcgowan** [comment]
My vote is for return codes, as a first  step.  This could later be augmented with some form of debug output (either via the existing _debug_output() to Serial/Serial1 or via cloud events, so that even when users don't check return codes, they can see there are problems. 

When I rework the Spark variables/functions/subscriptions to use dynamic memory, I will have to put in return codes, since whether it succeeds or fails is only determined at runtime, and cannot be known ahead of time.

@technobly - I think your intellisense popups for the ide is a great idea - why not post an feature request for that on webide/spark dev?

I'll close this issue since we can't take any action on the original problem.

**Comment by dmiddlecamp** [comment]
I'm not able to issue 'over limit' events on the cloud because the events are squelched by the firmware before it hits its limit serverside I think.  The cloud does send a 'too many messages' coap response to the core in the event of going over the limit, but we don't send a user-facing event yet I think.

**Comment by psb777** [comment]
OK, but for the avoidance of doubt, that is not good, assuming I understand what you say: The user code cannot tell whether or not the function call has succeeded. That's an awful paradigm in which to write applications.

**Comment by m-mcgowan** [comment]
@dmiddlecamp, sorry I wasn't clear - by cloud events. I was thinking of cloud-based logging from the core - not that the cloud somehow detects the limit has been reached. So the core publishes an warning logging event when Spark.function/Spark.variable etc fail. When coupled to the IDE this would allow users to see runtime errors in the IDE.

**Comment by technobly** [comment]
> So the core publishes an warning logging event when Spark.function/Spark.variable etc fail. When coupled to the IDE this would allow users to see runtime errors in the IDE.

I like this idea a lot, and it would also be great if users had control to turn error logging on and off (remotely and locally) to insure Spark.Pub/Sub was as fast as possible.

**Comment by dmiddlecamp** [comment]
Ah sure, my mistake, sounds great! :)
