### ISSUE TITLE
delay replacement

### ISSUE THREAD

**Issue by robertdolca** [spark/firmware#363]
When delay is used it make the CPU sleep for the specified amount of time. This is very annoying because if you wrote something with a big delay in loop the OTA is blocked. Can you write a wrapper over delay or make some changes to the way OTA works in order to avoid this issue?

**Comment by dmiddlecamp** [comment]
Could we modify the delay code to call the wlan loop more frequently?  I think delay still spends most of its time purely blocking, if we modified it to spend at least 50% of the time running the protocol pump, I suspect we would be able to OTA in the case where there is a `delay(1000);` in the user loop

**Comment by m-mcgowan** [comment]
We're already kind of doing that. `delay()` tries to run the event pump continually while there is a OTA flash in progress - please see https://github.com/spark/firmware/blob/master/src/spark_wiring.cpp#L659.  

So, once the OTA message is received, the system will sit in a tight loop pumping events, and not return control to user code.

@robertdolca please correct me if I'm wrong - my understanding that there was an infinite loop that was not calling delay, so the core is simply hung. Is that correct?

Also please note (and beware!) that there is also an internal function `Delay()` (note the uppercase D) which doesn't do any background processing. This should be avoided in general user code - `delay()` (lowercase) is the correct function to use.

**Comment by dmiddlecamp** [comment]
Right, what I mean is that the device isn't catching / responding to the UpdateBegin message sent from the server.  I think if we spent a greater percentage of time (instead of once every few seconds or so) running Spark.process, we'd have a greater chance of checking the receive buffer when the UpdateBegin message is sitting there, instead of it being missed.

**Comment by m-mcgowan** [comment]
Understood. As it is, the delays are cumulative - so even a tight loop with 1ms delays will eventually run the event pump once the accrued delay becomes greater than 1 second giving the device opportunity to receive and respond to the UpdateBegin message.

**Comment by robertdolca** [comment]
@m-mcgowan my question is: wouldn't it be a good idea to check for OTA updates using the timer interrupt if the last check was too long ago (the same one that is used for LED flashing)?

If the user code is while(1); there is no way to start OTA. What I am suggesting can be a solution for that.

**Comment by dmiddlecamp** [comment]
@robertdolca - sounds like you'd need to do some TCP operations to read through the pending messages from the server in order to figure out if an OTA is pending.  Interrupt functions need to be _very very_ fast, and I suspect that would have bad side-effects.  I think we played with this on a more infrequent timer, but it's hairy without an RTOS

**Comment by m-mcgowan** [comment]
Updating to the latest CC3000 service pack has been shown to improve the reliability of the cloud connection with long delays in user code.

On the photon, we will soon  have user code and system code executing on separate threads, so user code will not stop an OTA update from happening.
