### ISSUE TITLE
MANUAL mode should return control to the user loop if Cloud is not connected

### ISSUE THREAD

**Issue by mumblepins** [spark/firmware#366]
As per issue #357, wherein connect should have a retry limit, and issue #347 (to a certain degree) the current mode handling is a bit odd, both in terms of actuality as well as documentation.    The current way the main() loop works is that it if `Spark.connect()` is called, which sets the `SPARK_CLOUD_CONNECT = 1` flag, the `SPARK_WLAN_Loop()` call in the beginning of the `main()` loop will force a blockage of the user `loop()`.  This appears to be solely due to this line:
```c++
if(!SPARK_WLAN_SETUP || SPARK_WLAN_SLEEP || !SPARK_CLOUD_CONNECT || SPARK_CLOUD_CONNECTED || SPARK_WIRING_APPLICATION)
```
which must be true to proceed to the `setup()` or `loop()` user code sections.  This also maybe should pass if mode is SEMI_AUTOMATIC.

**Comment by m-mcgowan** [comment]
The first two points make sense - once the user code has deliberately disconnected wifi/cloud, there's little point in the system attempting to reconnect. That's the current behaviour today.

For unintentional disconnects, I feel the behaviour depends upon the mode. 

- In manual mode the system should not try to reconnect after an unintentional drop, since the rationale for manual mode is that any delays due to network operations are placed entirely under the user's control - the user code is responsible for detecting the cloud is down and initiating a connection when it can.

- In semi-automatic mode, the intent is that the user code initiates the cloud connection, and once connected, the system takes care of the cloud connection. After an unintentional disconnect, reconnection is handled by the system - the basic premise of semi-automatic mode being "maintain the cloud connection until I disconnect it."  This is also the behavior at present.

To make this behaviour clearer (as well as explicit and controllable) we could add a new connection property  

```Spark.maintainConnection(true|false)```

This sets whether the system attempts a reconnect after unintentional disconnect. Will be `false` by default for manual mode and `true` for other modes. This allows users to select the behaviour that makes most sense for their application, while also keeping the default behaviour we have today. It also provides an API point where we can more clearly document the behaviour with both intentional and unintentional disconnects.
