### ISSUE TITLE
Spark.function and Spark.variable should emit compile time warning if API endpoint is longer than 12 chars

### ISSUE THREAD

**Issue by topfunky** [spark/firmware#56]
If `Spark.function` is called with a `funcKey` that is longer than the allowed 12 characters, no error or warning is given, either at compile time or after being deployed to the device.

    Spark.function("reallylongfunctionname", deviceControl);

**What I Expected to Happen**

Some kind of warning would make it easier to debug this kind of error.

I did get a `return_value` of 4294967295 from the cloud when trying to POST to an endpoint that was too long.

https://github.com/spark/core-firmware/blob/master/src/spark_utilities.cpp

**Comment by m-mcgowan** [comment]
Just revisiting this. I agree a compile time error would be great if attainable. However, in the absence of this there are other measures we can take:
- return a success code from Spark.function/Spark.variable
- not register the variable/function if the name is too long rather than truncating it (and return a failure code.)

Thoughts?

**Comment by m-mcgowan** [comment]
The proposed `Particle.log` will post error events to the dashboard when API calls fail.
