### ISSUE TITLE
cppcheck static analysis results

### ISSUE THREAD

**Issue by brycekahle** [spark/firmware#815]
I ran [cppcheck](http://cppcheck.sourceforge.net/) against the firmware using
```
cppcheck -DPLATFORM_THREADING=0 -DPLATFORM_ID=3 -DPLATFORM_NAME=gcc -DUSBD_VID_SPARK=0x1D50 -DUSBD_PID_DFU=0x607F -DUSBD_PID_CDC=0x607D -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=3 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.8-rc.6 -DRELEASE_BUILD -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DMODULE_VERSION=0 -DMODULE_FUNCTION=3 -DMODULE_DEPENDENCY=0,0,0 -icommunication/lib ./
```

and it reported the following errors:
```
[communication/src/dtls_protocol.cpp:16]: (error) Using 'memset' on struct that contains a virtual method.
[hal/src/photon/softap.cpp:157]: (error) Common realloc mistake: 'tokens' nulled but not freed upon failure
[platform/NET/CC3000/CC3000_Host_Driver/wlan.c:657]: (error) Possible null pointer dereference: ucPf_OrKey
[services/src/debug.c:60]: (error) va_list 'args' was opened but not closed by va_end().
[services/src/debug.c:76]: (error) va_list 'args' was opened but not closed by va_end().
[user/applications/otastress/otastress.cpp:46]: (error) Using 'memset' on struct that contains a virtual method.
```

**Comment by m-mcgowan** [comment]
Thanks for running this - just 6 flags for the whole codebase! I'm pretty happy with that!

I checked out these error flags and thankfully they are mostly benign, so no consquence for firmware in the field. I'll try to work around them since it's a good starting point to have 0 errors so that we can introduce this to our CI process and then spot any new errors that are introduced. 

- memset on a struct with virtual functions: dtls_protocol.cpp: the Callbacks struct is a collection of plain function pointers - it's not virtual, so there's no hidden virtual table pointer to accidentally overwrite. I changed the intiialization to use assignment rather than memset to work around the flag.

- common realloc mistake: this was a good catch, that would cause a memory leak if there was insufficient memory. 

- Possible null pointer dereference: ucPf_OrKey: This falls into an unverifiable area where there are dependent parameters. The assumption being that ucPf_OrKey is set for WPA/WPA2/WEP security, and that also the ulPassPhraseLen is set to be the corresponding length. Static analysis can't show that these conditions are true.  I've added an explicit null pointer check to defeat this false alarm. 

- va_list 'args' was opened but not closed by va_end():  this is good practice, so I added the missing calls.  va_end() is a no-op when parameters are passed on the stack (as they are with most C++ ABIs), so no actual consequence beyond raising this flag.

- otastress.cpp:46]: (error) Using 'memset' on struct:  removed the virtual function since it wasn't needed.
