### ISSUE TITLE
Particle.variable(float) produces odd result (float gets treated as double)

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#842]
https://community.particle.io/t/string-tofloat-oddities/19530/2

Despite the title of the topic the problem is not `String::toFloat()` but as it seems that you can pass a `float` to `Particle.variable()` but the cloud side of things tries to take it as `double` 

```cpp
float foo;
Particle.variable("Foo", foo);
```
is reported by `particle list` as 
```text
  Variables:
    Foo (double)
```
and `particle get MyDev Foo` reports `5.2648096829335064e-270` instead of `123.12300` (tested with `Serial.println(foo, 5)`).

**Comment by ScruffR** [comment]
Is this meant to be the final word on this or just a workaround for the time being?

What would `Particle.variable("foo", (double)floatVar)` do?

The "new" two-param overload somehow obscures what datatypes are supported, and I thought this was meant to support arbitrary datatypes after all.

**Comment by m-mcgowan** [comment]
Github closes issues sometimes based on commit comments. It's not intended to be a final word - is there ever a final word with continually evolving systems?

The commit is there to directly catch cases where float is used.  Sure, casting to a double passes the compiler checks for now, although I'm surprised it doesn't complain about taking the address of a temporary. 

We will be revising the inner workings of variables soon. I'll see if we can have float support added to the cloud since this topic has come up several times before and seems to be a source of confusion.

**Comment by ScruffR** [comment]
Yup, no build message with the cast but still the same result.

**Comment by m-mcgowan** [comment]
We aill add 2 changes to variables:

- on demand computation of the variable value, for things like WiFi.localIP()
- detection of when a variable is on the stack -  the registration will not succeed, to prevent a potentially difficult situation.
