### ISSUE TITLE
Wrap DNS lookup in a friendly user function

### ISSUE THREAD

**Issue by zsup** [spark/firmware#91]
https://community.sparkdevices.com/t/hard-coded-ip-a-good-idea/804/3

**Comment by m-mcgowan** [comment]
How about:

```
IPAddress address = Network.resolve("my.domain.com")
```

**Comment by bkobkobko** [comment]
How about WiFi.resolve("my.domain.com") instead since the network object was deprecated (unless you are bringing it back).

**Comment by m-mcgowan** [comment]
Yes, we will be bringing back `Network` for services that are connection-agnostic. WiFi will extend Network so WiFi.resolve() would also be available.

**Comment by bkobkobko** [comment]
Hi @m-mcgowan  Matt,

I have code for this for Spark that I have not submitted due to one less-than-ideal use case that I ran into with this on the core. If you provide Network.resolve(hostname) then people will want to use it like they do IPAddress in a global variable set at boot up time.  

The problem is that the network is not running when this needs to initialize so you either have to error out which is not ideal and user unfriendly **or** use deferred or lazy evaluation of some kind which is hard.

```cpp
IPAddress myHost = Network.resolve("my.host.com");

void setup() {
...
}
void loop() {
...
}
```
I am not saying this impossible, it is just needs a lot of doc and user education to avoid what I think will be the first thing most people try.

**Comment by andyw-lala** [comment]
Is there an option to do anything at least semi-useful at compile time, by
having the cloud do a lookup ?

Seems that is almost as valid as just doing it at startup, for the _vast_
majority of hostnames out there. Both run the risk of going stale over time.

Yeah - I realize this is kind of a dumb idea, but I wanted to throw it out
there.

On Tue, Apr 21, 2015 at 9:41 PM, Brian Ogilvie <notifications@github.com>
wrote:

> Hi @m-mcgowan <https://github.com/m-mcgowan> Matt,
>
> I have code for this for Spark that I have not submitted due to one
> less-than-ideal use case that I ran into with this on the core. If you
> provide Network.resolve(hostname) then people will want to use it like they
> do IPAddress in a global variable set at boot up time.
>
> The problem is that the network is not running when this needs to
> initialize so you either have to error out which is not ideal and user
> unfriendly *or* use deferred or lazy evaluation of some kind which is
> hard.
>
> IPAddress myHost = Network.resolve("my.host.com");
> void setup() {
> ...
> }void loop() {
> ...
> }
>
> I am not saying this impossible, it is just needs a lot of doc and user
> education to avoid what I think will be the first thing most people try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/91#issuecomment-95004819>.
>



-- 
Andy

**Comment by m-mcgowan** [comment]
@bko - good points. We should definitely have the example doc showing resolve being called from setup()

```
IPAddress myServer;
void setup() {
   myServer = WiFi.resolve("my.host.com")
}
```
