### ISSUE TITLE
APPDIR for monolithic firmware

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#970]
Building with this command doesn't use the correct application (tinker is used instead):

`~/Programming/firmware/main$ make clean all PLATFORM=photon USE_SWD_JTAG=y MODULAR=n APPRDIR=~/Programming/PhotonApps/wifi_lockup`

Using APP instead of APPDIR works. Building with MODULAR=y and APPDIR works.

**Comment by technobly** [comment]
Sorry I didn't catch this sooner since I always use APPDIR and it works fine.  Staring at your command I found a simple typo `APPRDIR` instead of `APPDIR`.  If you use this command it will work:

`~/Programming/firmware/main$ make clean all PLATFORM=photon USE_SWD_JTAG=y MODULAR=n APPDIR=~/Programming/PhotonApps/wifi_lockup`
